### ISSUE TITLE
When window maximized the content stay fixed and do not adjust with the new screen

### ISSUE THREAD

**Issue by sediq-khan** [k33ptoo/RestaurantMgtSampleUI#2]
I have removed the:

`primaryStage.initStyle(StageStyle.UNDECORATED);`

And now when I maximize the window following is what I see. How do I make it responsive?
![image](https://user-images.githubusercontent.com/11982020/63271686-f6a0db80-c29a-11e9-9163-204e326d6b2d.png)

**Comment by k33ptoo** [comment]
I didn't make the ui responsive unfortunately, you have to change the Pane to a BorderPane so you add the components to specific locations.
